### ISSUE TITLE
[Bug]: toLocal() inconsistent return values

### ISSUE THREAD

**Issue by xtfer** [grantholle/laravel-timezone#6]
### What happened?

toLocal() is documented as not requiring a format, but if one isn't passed you get back a CarbonImmutable object instead of a string. Not technically a bug since the return value is string|CarbonImmutable, but sufficiently inconsistent.

### How to reproduce the bug

toLocal() is documented as not requiring a format, but if one isn't passed you get back a CarbonImmutable object instead of a string. Not technically a bug since the return value is string|CarbonImmutable, but sufficiently inconsistent.

### Package Version

latest

### PHP Version

8.1

### Laravel Version

10.x

**Comment by grantholle** [comment]
Yes, this is the intended behavior. I've updated the readme to be a little more explicit rather than relying on variable names. Without a second parameter, the return value will be a `CarbonImmutable` instance.

If you always want a return value to be a formatted string, you can use the `Timezone::toLocalFormatted()` function, which always returns a string even when you do not provide a format value as the second parameter. It will rely on your `config('timezone.format')` value.
